kasia_epopee_homepage:
    path:     /home
    defaults: { _controller: KasiaEpopeeBundle:Default:index }

kasia_epopee_book:
    path:     /book/{book}
    defaults: { _controller: KasiaEpopeeBundle:Default:book }
